<?php
/**
* This file is used only to sync the translations from twig to the .po & .mo files
*/

__('Nutrition Facts', 'zip-recipes');
__('Serves', 'zip-recipes');
__('Amount Per Serving', 'zip-recipes');
__('Calories', 'zip-recipes');
__('% Daily Value*', 'zip-recipes');
__('Total Fat', 'zip-recipes');
__('Saturated Fat', 'zip-recipes');
__('Trans Fat', 'zip-recipes');
__('Cholesterol', 'zip-recipes');
__('Sodium', 'zip-recipes');
__('Total Carbohydrate', 'zip-recipes');
__('Total Carbohydrate', 'zip-recipes');
__('Dietary Fiber', 'zip-recipes');
__('Sugars', 'zip-recipes');
__('Protein', 'zip-recipes');
__('Vitamin A', 'zip-recipes');
__('Vitamin C', 'zip-recipes');
__('Vitamin C', 'zip-recipes');
__('Iron', 'zip-recipes');
__('* Percent Daily Values are based on a 2,000 calorie diet. Your daily values may be higher or lower depending on your calorie needs.', 'zip-recipes');
__('Like the plugin, or need more features?','zip-recipes');
__('Ingredients','zip-recipes');
__('Instructions','zip-recipes');
__('Instructions List Type','zip-recipes');
__('Prep Time:','zip-recipes');
__('Cook Time:','zip-recipes');
__('Total Time:','zip-recipes');
__('Cuisine:','zip-recipes');
__('Servings:','zip-recipes');
__('Serving Size:','zip-recipes');
__('Calories per serving:','zip-recipes');
__('Fat per serving:','zip-recipes');
__('Saturated fat per serving:','zip-recipes');
__('Carbs per serving:','zip-recipes');
__('Protein per serving:','zip-recipes');
__('Fiber per serving:','zip-recipes');
__('Sugar per serving:','zip-recipes');
__('Sodium per serving:','zip-recipes');
__('Trans fat per serving:','zip-recipes');
__('Cholesterol per serving:','zip-recipes');
__('stars','zip-recipes');
__('Your rating:','zip-recipes');
__('Rate this recipe','zip-recipes');
__('ratings','zip-recipes');
__('Rating','zip-recipes');
__('Prep','zip-recipes');
__('Cook','zip-recipes');
__('Ready in','zip-recipes');
__('Notes','zip-recipes');
__('Nutrition information', 'zip-recipes');
__('Save to BigOven','zip-recipes');
__('Category:','zip-recipes');
__('Author:','zip-recipes');
__('Fiber:','zip-recipes');
__('Calories:','zip-recipes');
__('Carbs:','zip-recipes');
__('Cholesterol:','zip-recipes');
__('Choose an option','zip-recipes');
__('Fat:','zip-recipes');
__('Protein:','zip-recipes');
__('Sodium:','zip-recipes');
__('Total:','zip-recipes');
__('Error','zip-recipes');
__('Trans fat:','zip-recipes');
__('Start','zip-recipes');
__('Saturated fat:','zip-recipes');
__('Prep:','zip-recipes');
__('Print this recipe','zip-recipes');
__('Prep Time','zip-recipes');
__('Cook Time','zip-recipes');
__('Clear label','zip-recipes');
