<?php
/**
 * This file is used only to sync the translations from twig to the .po & .mo files
 */

__('Like this plugin? The premium version includes lots of cool extra features, your ','zip-recipes');
__('20% fast adapter discount','zip-recipes');
__(' is still valid!','zip-recipes');
__("check out premium","zip-recipes");
__("apply discount","zip-recipes");
__("dismiss","zip-recipes");
__('For the best performance, Zip Recipes recommends ImageMagick or GD PHP extensions installed. Please contact your hosting company and request that they install ImageMagick or GD PHP extensions for you website.','zip-recipes');
__('Nutrition Facts', 'zip-recipes');
__('Serves', 'zip-recipes');
__('Amount Per Serving', 'zip-recipes');
__('Calories', 'zip-recipes');
__('% Daily Value*', 'zip-recipes');
__('Total Fat', 'zip-recipes');
__('Saturated Fat', 'zip-recipes');
__('Trans Fat', 'zip-recipes');
__('Cholesterol', 'zip-recipes');
__('Sodium', 'zip-recipes');
__('Total Carbohydrate', 'zip-recipes');
 __('Total Carbohydrate', 'zip-recipes');
__('Dietary Fiber', 'zip-recipes');
__('Sugars', 'zip-recipes');
__('Protein', 'zip-recipes');
__('Vitamin A', 'zip-recipes');
__('Vitamin C', 'zip-recipes');
__('Vitamin C', 'zip-recipes');
__('Iron', 'zip-recipes');
__('* Percent Daily Values are based on a 2,000 calorie diet. Your daily values may be higher or lower depending on your calorie needs.', 'zip-recipes');
__('Ingredients','zip-recipes');
__('Put each ingredient on a separate line.  There is no need to use bullets for your ingredients.<br />
                        You can also create labels, hyperlinks, bold/italic effects and even add images!','zip-recipes');
 __('Instructions','zip-recipes');
 __('Like the plugin, or need more features?','zip-recipes');
 __('Optimized for Google','zip-recipes');
__('Cool looking themes','zip-recipes');
__('Automatic serving adjustment','zip-recipes');
__('Author setting for Google','zip-recipes');
 __('Ratings and reviews','zip-recipes');
 __('Save recipes on social media','zip-recipes');
__('Recipe index','zip-recipes');
__('Automatic nutrition calculation','zip-recipes');
__('Search by ingredients','zip-recipes');
__('Recipe picture gallery','zip-recipes');
__('Mobile friendly','zip-recipes');
 __('Zip Recipes Settings','zip-recipes');
 __('For more customization options, see our knowledgebase:','zip-recipes');
__('Custom Print Button','zip-recipes');
__('Zip Recipes Plugin Link','zip-recipes');
__('Printed Output: Recipe Permalink','zip-recipes');
__('Printed Output: Copyright Statement','zip-recipes');
__('Recipe Card Look & Feel','zip-recipes');
__('Stylesheet','zip-recipes');
 __('Recipe Title','zip-recipes');
 __('Print Button','zip-recipes');
__('Hide image when duplicate of post','zip-recipes');
__('Image Width','zip-recipes');
 __('Image Display','zip-recipes');
__('Border Style','zip-recipes');
 __('Ingredients','zip-recipes');
__('Ingredients Label','zip-recipes');
 __('Ingredients List Type','zip-recipes');
__('List','zip-recipes');
__('Numbered List','zip-recipes');
__('Bulleted List','zip-recipes');
__('Paragraphs','zip-recipes');
__('Divs','zip-recipes');
 __('Instructions','zip-recipes');
 __('Instructions Label','zip-recipes');
 __('Instructions List Type','zip-recipes');
__('Other Options','zip-recipes');
__('Use Zip Recipes style','zip-recipes');
__('Hide Recipe Title in post (still shows in print view)','zip-recipes');
__('Hide Print Button','zip-recipes');
__('Hide image when duplicate of post','zip-recipes');
 __('Hide recipe image when recipe image is the same as the post image','zip-recipes');
__('Image Width','zip-recipes');
 __('Image Display','zip-recipes');
__('Hide Image in post','zip-recipes');
__('Hide Image in print view','zip-recipes');
__('Print', 'zip-recipes');
__('Prep Time:','zip-recipes');
__('Cook Time:','zip-recipes');
__('Total Time:','zip-recipes');
__('Cuisine:','zip-recipes');
__('Servings:','zip-recipes');
 __('Serving Size:','zip-recipes');
__('Calories per serving:','zip-recipes');
__('Fat per serving:','zip-recipes');
 __('Saturated fat per serving:','zip-recipes');
__('Carbs per serving:','zip-recipes');
 __('Protein per serving:','zip-recipes');
__('Fiber per serving:','zip-recipes');
__('Sugar per serving:','zip-recipes');
 __('Sodium per serving:','zip-recipes');
 __('Trans fat per serving:','zip-recipes');
__('Cholesterol per serving:','zip-recipes');
__('Ingredients','zip-recipes');
 __('stars','zip-recipes');
__('Your rating:','zip-recipes');
 __('Rate this recipe','zip-recipes');
__('ratings','zip-recipes');
__('Rating','zip-recipes');
__('Prep','zip-recipes');
__('Cook','zip-recipes');
 __('Ready in','zip-recipes');
 __('Notes','zip-recipes');
 __('Nutrition information', 'zip-recipes');
__('Save to BigOven','zip-recipes');
__('Category:','zip-recipes');
 __('Author:','zip-recipes');
__('Fiber:','zip-recipes');
__('Calories:','zip-recipes');
__('Carbs:','zip-recipes');
__('Cholesterol:','zip-recipes');
__('Choose an option','zip-recipes');
__('Deactivate License','zip-recipes');
__('Fat:','zip-recipes');
__('Protein:','zip-recipes');
__('Sodium:','zip-recipes');
__('Total:','zip-recipes');
__('Error','zip-recipes');
__('Trans fat:','zip-recipes');
__('You do not have permission to install plugin updates','zip-recipes');
__('Use custom authors','zip-recipes');
__('Use custom authors instead of default WordPress post authors.','zip-recipes');
__('Start','zip-recipes');
__('Saturated fat:','zip-recipes');
__('Recipe Reviews','zip-recipes');
__('Prep:','zip-recipes');
__('Print this recipe','zip-recipes');
__('Prep Time','zip-recipes');
__('Generate label','zip-recipes');
__('Enter your license key','zip-recipes');
__('Cook Time','zip-recipes');
__('Clear label','zip-recipes');
__('Activate License','zip-recipes');
__('active','zip-recipes');
__('An error occurred while updating the license data, please try again.','zip-recipes');
